require "test_helper"

describe Day14 do
  def setup
    @d = Day14.new
    @d.test_input <<~TEST
      498,4 -> 498,6 -> 496,6
      503,4 -> 502,4 -> 502,9 -> 494,9
    TEST
  end

  def test_cave
    cave = Day14::Cave.new(@d.raw_input)
    assert_equal <<~CAVE.chomp, cave.to_s
      ......+...
      ..........
      ..........
      ..........
      ....#...##
      ....#...#.
      ..###...#.
      ........#.
      ........#.
      #########.
    CAVE
    cave.fill
    assert_equal <<~CAVE.chomp, cave.to_s
      ......+...
      ..........
      ......o...
      .....ooo..
      ....#ooo##
      ...o#ooo#.
      ..###ooo#.
      ....oooo#.
      .o.ooooo#.
      #########.
    CAVE
    cave.add_floor
    assert_equal <<~CAVE.chomp, cave.to_s
      ...........+...........
      .......................
      ...........o...........
      ..........ooo..........
      .........#ooo##........
      ........o#ooo#.........
      .......###ooo#.........
      .........oooo#.........
      ......o.ooooo#.........
      .....#########.........
      .......................
      #######################
    CAVE
    cave.fill
    assert_equal <<~CAVE.chomp, cave.to_s
      ...........o...........
      ..........ooo..........
      .........ooooo.........
      ........ooooooo........
      .......oo#ooo##o.......
      ......ooo#ooo#ooo......
      .....oo###ooo#oooo.....
      ....oooo.oooo#ooooo....
      ...oooooooooo#oooooo...
      ..ooo#########ooooooo..
      .ooooo.......ooooooooo.
      #######################
    CAVE
  end

  def test_fill2
    cave = Day14::Cave.new(@d.raw_input)
    cave.add_floor
    cave.fill2
    assert_equal <<~CAVE.chomp, cave.to_s
      ...........o...........
      ..........ooo..........
      .........ooooo.........
      ........ooooooo........
      .......oo#ooo##o.......
      ......ooo#ooo#ooo......
      .....oo###ooo#oooo.....
      ....oooo.oooo#ooooo....
      ...oooooooooo#oooooo...
      ..ooo#########ooooooo..
      .ooooo.......ooooooooo.
      #######################
    CAVE
  end

  def test_part1
    assert_equal 24, @d.part1
  end

  def test_part2
    assert_equal 93, @d.part2
  end
end
