---
AllCops:
  TargetRubyVersion: 2.7
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Metrics/LineLength:
  Max: 120
Naming/MethodParameterName:
  Enabled: false
