---
name: Test
"on":
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    name: ruby
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
          # no bundler, stdlib only
      - run: rake test
